export const CHANGE_MOVING_TOTAL = "change_moving_total"
export const CHANGE_CURRENT_MAP = "change_current_map"
export const MOVE_CURRENT_MAP = "move_current_map"
export const CHANGE_ROLE = "change_role"
export const CHANGE_GO_BACK = "change_go_back"
export const CLEAR_GO_BACK = "clear_go_back"
export const CHANGE_MAP_LEVEL = "change_map_level"
